name: MY CI
on: 
  push:
    branches: 
      - main
      - release/*
jobs:
  test:
    name: one job
    runs-on: ubuntu-latest
    steps:
      - name: Collect the number of stars
        run: echo "Collect the number of stars"
   


