name: MY CI
on: 
  schedule:
    - cron: "30 5 * * ?"
  push:
    branches: 
      - main
      - release/*
jobs:
  update-readme-with-blog: 
    name: update readme 
    runs-on: ubuntu-latest
    steps:
      - name: update readme
        run: echo "update readme" > README.md
      - name: Commit and push if changed
        run:
          git add .
          git commit -m 'update README.md'
          git push
      
  test:
    name: one test job
    runs-on: ubuntu-latest
    steps:
      - name: one test job
        run: echo "one test job"
   


